### ISSUE TITLE
Mordred continuously exiting with "Exit 127"

### ISSUE THREAD

**Issue by mbbroberg** [grimoirelab/mordred#25]
👋  Hey all, been trying to get your example of Mordred up and running from the example folder. I've made all the directory calls relative to the path and included a copy of the docker-compose file [on my branch here](https://github.com/mbbroberg/mordred/tree/docker/docker/example_conf). 

Once I run it (`docker-compose up -d`, I get into Kibana but do not have any items in ES as visible here: 

![screen shot 2017-06-01 at 11 36 00 am](https://cloud.githubusercontent.com/assets/1744971/26695127/8dec3fa8-46be-11e7-933d-a6596bcffe2e.png)

I believe it is due to an error with Mordred running to completion. I can see it fails [in this gist](https://gist.github.com/mbbroberg/542a6302938674c3700f6c20623f741d)

**Comment by sanacl** [comment]
Hey @mbbroberg, this looks like you are not using the latest version of the bitergia/mordred container. Please execute ```docker pull bitergia/mordred```, stop and remove the current mordred container and run the compose again with ```up -d```

**Comment by aghassabian** [comment]
@sanacl  Hi, I'm using the latest Mordred and follow the instruction to all docker containers to be loaded. after a minute the Mordred docker stops, so the process is not completed and neither index nor dashboard creates. I checked the logs of the Mordred container. The logs mention that the reason is the sortinghat matching class type should be list not string as follows:

 `File "./mordred/config.py", line 460, in check_config
    raise RuntimeError(msg)
RuntimeError: Wrong type for section param: sortinghat matching <class 'str'> should be <class 'list'>`

I checked the source code and surprisingly noticed the matching type is "list" as follows:

`params_sortinghat = {`
 `          "sortinghat": {`
 `               "unaffiliated_group": {`
 `                   "optional": False,`
  `                  "default": "Unknown",`
  `                  "type": str`
  `             },`
  `              "unify_method": {  # not used`
  `                  "optional": True,`
  `                  "default": "fast-matching",`
  `                  "type": str`
  `              },`
  `              "matching": {`
  `                  "optional": False,`
  `                  "default": ["email"],`
  `                  "type": list`
Do you have any idea what is the real source of the problem?
Thanks for your help in this matter in advance.

**Comment by acs** [comment]
Pretty old ticket. mordred has changed a lot since then.

@mbbroberg if you have issues with the current version of mordred, please open a new ticket.

Thank you very much for your contribution!
