### ISSUE TITLE
Useless log message about refreshing identities fields

### ISSUE THREAD

**Issue by sanacl** [grimoirelab/mordred#41]
Using master version of GrimoireELK+Mordred I've seen this log message:

`2017-11-14 13:33:48,247 - mordred.task_enrich - INFO - Refreshing identities fields in enriched index                                                                                         
`

It does not add any useful information. 

So it should contain:
- the name of the index it is refreshing
- the number of identities to be refreshed (wishlist)

**Comment by acs** [comment]
The message is not totally useless but yes, we need to improve it. 

The new one:

`
2017-11-15 06:25:48,376 Refreshing identities fields in http://bitergia:bitergia@localhost:9200/git
`

The same fix done for refreshing projects.

This bug should be opened in GrimoireELK.

Fixed in https://github.com/grimoirelab/GrimoireELK/commit/568b937bf9e47594bd03c4b9a06549caa0dac18a
